# Generated by Django 3.1.2 on 2020-10-26 15:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bdoessentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone2',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
