# Generated by Django 3.1.2 on 2020-10-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdoessentials', '0002_auto_20201026_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone1',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone2',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
